#Pipeline de Deploy no Azure Portal
#Serviço usado: Azure Static Web App
#Pipeline no repos do github

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CopyFiles
    jobs:
      - job: CopyFiles
        steps:
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'sonarcloud'
              organization: 'ynocce'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'ynocce_portfolio-CI-CD'
              cliProjectName: 'portfolio-CI-CD'
              cliSources: '.'

          - task: SonarCloudPublish@1
            inputs:
              pollingTimeoutSec: '300'
          - task: SonarCloudAnalyze@1
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'
          - task: CopyFiles@2
            displayName: "Copiando Arquivos do repos"
            inputs:
              Contents: 'portifolio.integrado.azureDevOps/**'
              TargetFolder: $(build.artifactstagingdirectory)

          - task: PublishBuildArtifacts@1
            displayName: "Criando um artefato com os arquivos"
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure-DevOps-Subscription(a454e4e9-14dc-442e-9d50-a76534f9aef6)'
              appType: 'webApp'
              WebAppName: 'mey-service'
              packageForLinux: '$(System.ArtifactsDirectory)/drop/**'