#Pipeline de Deploy no Azure Portal
#Serviço usado: Azure Static Web App
#Pipeline no repos do github

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CopyFiles
    jobs:
      - job: CopyFiles
        steps:
          - tawsk: CopyFiles@2
            displayName: "Copiando Arquivos do repos"
            inputs:
              Contents: 'portifolio.integrado.azureDevOps/**'
              TargetFolder: $(build.artifactstagingdirectory)

          - task: PublishBuildArtifacts@1
            displayName: "Criando um artefato com os arquivos"
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'