#Pipeline de Deploy no Azure Portal
#Serviço usado: Azure Static Web App
#Pipeline no repos do github

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# - task: AzureStaticWebApp@0
#   inputs:
#     app_location: 'portifolio.integrado.azureDevOps'
#     azure_static_web_apps_api_token: '$(token)'
- task: CopyFiles@2
  inputs:
    # SourceFolder: 'portfolio-CI-CD'
    Contents: '**'
    TargetFolder: $(build.artifactstagingdirectory)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'