#Pipeline de Deploy no Azure Portal
#Serviço usado: Azure Static Web App
#Pipeline no repos do github

trigger:
- main

pool:
  vmImage: Ubunto 64-bit

steps:

- task: AzureStaticWebApp@0
  inputs:
    app_location: 'portifolio.integrado.azureDevOps'
    azure_static_web_apps_api_token: '$(token)'
