#Pipeline de Deploy no Azure Portal
#Serviço usado: Azure Static Web App
#Pipeline no repos do github

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage:
    jobs:
      - job: 
        steps:
          - task: CopyFiles@2
            inputs:
              Contents: 'portifolio.integrado.azureDevOps/**'
              TargetFolder: $(build.artifactstagingdirectory)

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'