#Pipeline de Deploy no Azure Portal
#Serviço usado: Azure Static Web App
#Pipeline no repos do github

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: CopyFiles
    jobs:
      - job: CopyFiles
        steps:
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'sonarcloud'
              organization: 'ynocce'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'ynocce_portfolio-CI-CD'
              cliProjectName: 'portfolio-CI-CD'
              cliSources: '.'

          - task: SonarCloudPublish@1
            inputs:
              pollingTimeoutSec: '300'
          - task: SonarCloudAnalyze@1
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure-DevOps-Subscription(a454e4e9-14dc-442e-9d50-a76534f9aef6)'
              appType: 'webApp'
              WebAppName: 'mey-service'
          
          - task: AzureStaticWebApp@0
            inputs:
              app_location: 'portifolio.integrado.azureDevOps'
              azure_static_web_apps_api_token: '$(token)'