#Pipeline de Deploy no Azure Portal
#Serviço usado: Azure Static Web App

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureStaticWebApp@0
  inputs:
    app_location: 'portifolio.integrado.azureDevOps'
    azure_static_web_apps_api_token: '$(token)'
