#Essa pipeline tem como objetivo realizar deploy na Azure
#A mesma está integrada com o Azure DevOps em um esteira automatizada CI/CD
#Deploy será feito em um Azure Static Web.

trigger:
- main

pool:
  vmImage: windows-latest

steps:

# - task: AzureFileCopy@5
#   inputs:
#     SourcePath: 'index.html'
#     azureSubscription: 'Azure-DevOps-Subscription(a454e4e9-14dc-442e-9d50-a76534f9aef6)'
#     Destination: 'AzureBlob'
#     storage: 'testedevopsgit'
#     ContainerName: '$web'

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Azure-DevOps-Subscription(1)(a454e4e9-14dc-442e-9d50-a76534f9aef6)'
    ScriptType: 'InlineScript'
    Inline: |
      # upload a file
      set-AzStorageblobcontent -File "index.html" `
      -Container `$web `
      -Blob "testedevopsgit" `
      -Context $ctx
    azurePowerShellVersion: 'LatestVersion'